"""empty message

Revision ID: 2f59255c9c3c
Revises: b515afbde9d5
Create Date: 2021-04-25 01:07:47.793821

"""

# revision identifiers, used by Alembic.
revision = '2f59255c9c3c'
down_revision = 'b515afbde9d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
