"""empty message

Revision ID: 9ffa84629514
Revises: 0a97f9b42821
Create Date: 2021-04-25 00:25:51.955179

"""

# revision identifiers, used by Alembic.
revision = '9ffa84629514'
down_revision = '0a97f9b42821'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
