"""empty message

Revision ID: e0fea9ff34df
Revises: 456a945560f6
Create Date: 2021-04-17 22:10:30.069219

"""

# revision identifiers, used by Alembic.
revision = 'e0fea9ff34df'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
