"""empty message

Revision ID: 1e48f6b7eb4a
Revises: a95c99433dc4
Create Date: 2021-05-08 17:30:42.689833

"""

# revision identifiers, used by Alembic.
revision = '1e48f6b7eb4a'
down_revision = 'a95c99433dc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
