"""sth

Revision ID: 4db72dbcc6b3
Revises: 54f1dec0e87d
Create Date: 2021-05-15 21:30:50.686937

"""

# revision identifiers, used by Alembic.
revision = '4db72dbcc6b3'
down_revision = '54f1dec0e87d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
