"""empty message

Revision ID: d629162cee2a
Revises: e0fea9ff34df
Create Date: 2021-04-17 22:11:59.031722

"""

# revision identifiers, used by Alembic.
revision = 'd629162cee2a'
down_revision = 'e0fea9ff34df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
