"""empty message

Revision ID: de6d4cfc4dc5
Revises: 1e48f6b7eb4a
Create Date: 2021-05-08 17:35:53.904224

"""

# revision identifiers, used by Alembic.
revision = 'de6d4cfc4dc5'
down_revision = '1e48f6b7eb4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
